# Generated by Django 3.1.3 on 2021-01-02 19:09

from django.db import migrations, models
import django.utils.timezone
import markdownx.models
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='published',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='note',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.AlterField(
            model_name='note',
            name='note_body',
            field=markdownx.models.MarkdownxField(),
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
