# Generated by Django 3.1.3 on 2021-01-04 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_auto_20210102_1909'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='trashed',
            field=models.BooleanField(default=False),
        ),
    ]
